name: Deploy Hexo site to Vercel

env:
    VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
    deployment

jobs:
    deploy:
        runs-on: ubuntu-22.04
        steps:
          - name: Checkout
            uses: actions/checkout@v3
          - name: Deploy Project Artifacts to Vercel
            run: vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}
          - name: Clean
            run: vercel remove arcoe --safe --yes --token=${{ secrets.VERCEL_TOKEN }}